#!/usr/bin/python3
import sys
import requests
import datetime
import lxml.html as lh
from os.path import isfile, expanduser
from termcolor import colored
url = 'https://www.gov.uk/guidance/red-amber-and-green-list-rules-for-entering-england'
cmap = {}
colours = ['red', 'amber', 'green']
home = expanduser('~')
log_file = f'{home}/.go2uk.db'


def flag():
    return 'r' if isfile(log_file) else 'w+'


def log():
    with open(log_file, flag()) as db:
        return db.read()


def populate():
    print('fetching recent data from gov.uk...')
    page = requests.get(url)
    doc = lh.fromstring(page.content)
    for tables in doc.xpath('//table'):
        colour = None
        for table in tables:
            if table.tag == 'thead':
                colour = table.text_content().split()[0].lower()
                cmap[colour] = []
            else:
                countries = [name for name in table.text_content().split('\n')
                             if len(name.strip()) > 1 and not name.strip().startswith('Moved')]
                for c in countries:
                    key = c.strip().split()[0].lower()
                    cmap[key] = colour
                    cmap[colour].append(c.strip())
    write_entry()


def show_colour(*colours):
    delimit = '\n* '
    for colour in colours:
        cs = cmap[colour]
        text_colour = "yellow" if colour == "amber" else colour
        print(
            f'{colored(colour.capitalize(), text_colour)} ({len(cs)} countries):', end=delimit)
        print(delimit.join(cs))
        print()


def fetch_or_read():
    existing_data = log()
    lines = existing_data.split('\n')
    current = datetime.datetime.now()
    recent = None if not existing_data else datetime.datetime.strptime(
        lines[0].strip(), '%Y-%m-%d %H:%M:%S.%f')
    if not recent or current.day > recent.day or current.hour - recent.hour > 5:
        populate()
    else:
        for line in lines[1:4]:
            parts = line.split(':')
            col = parts[0].strip()
            cs = parts[1].split('/')
            cmap[col] = []
            for country in cs:
                cmap[col].append(country)
                country_key = country.split('(')[0].strip().lower()
                cmap[country_key] = col
        print(f'(retrieved data from ./{log_file} at {str(recent)})')


def write_entry():
    timestamp = datetime.datetime.now()
    data = log()
    with open(log_file, 'w+') as db:
        entry = f'{str(timestamp)}'
        for key in cmap:
            if key in colours:
                entry += f'\n{key}:{"/".join(cmap[key])}'
        db.write(entry + '\n' + data)
    print(f'(wrote new entry to ./{log_file} at {str(timestamp)})')


def remove_arg(arg):
    i = sys.argv.index(f'--{arg}')
    del sys.argv[i]


if '--fetch' in sys.argv:
    remove_arg('fetch')
    populate()
else:
    fetch_or_read()

if len(sys.argv) > 1:
    arg = sys.argv[1].strip().lower()
    if arg in colours:
        show_colour(arg)
    elif arg in cmap:
        colour = cmap[arg]
        print(
            f'{arg.capitalize()}: {colored(colour, "yellow" if colour == "amber" else colour)}')
    else:
        print(f'Couldn\'t find country {colored(arg.capitalize(), "blue")}')
else:
    show_colour(*colours)
